### ISSUE TITLE
Environment variables aren't loaded

### ISSUE THREAD

**Issue by ajagnanan** [SC5/serverless-mocha-plugin#1]
Looks like when you run tests, it doesn't inject environment variables configured in s-function.json

**Comment by AniAko** [comment]
I don't understand how this plugin can be of any use without this functionality. :( ???

**Comment by AniAko** [comment]
I've added the support in pull request #8

**Comment by mpuittinen** [comment]
Thanks, that has now been merged to the module. I made some fixes to get the region and stage evaluated properly. I'll merge some other PRs and then release a new version of the module
