### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ecoruh** [SC5/serverless-mocha-plugin#13]
I followed your README. I have a very simple function ```function1``` (created via serverless tutorial). I ran ```mocha-create``` and ```mocha-run``` commands under serverless project root.

Creation worked OK:
```
$ sls function mocha-create function1
serverless-mocha-plugin: created test\function1.js
```
However ```mocha-run``` returned this error:
```
$ sls function mocha-run function1
Unhandled rejection Error: Cannot find module '../functions♀unction1/handler.js'
```
note: the module has this funny ```♀``` character in stead of ```/f```.

**Comment by ecoruh** [comment]
The issue was ```path.relative``` returns relative path in native form, under windows it uses non-posix path separator ```\```.  Injecting ```replace``` at ```index.js``` at line  242 like this fixed the issue:
```
let funcPath = path.relative(projectPath, funcFullPath).replace(/\\/g, "/");
```

**Comment by ecoruh** [comment]
I could fix this with a pull request but never done it, if you show me I can happily contribute and fix it via pull request..

**Comment by laardee** [comment]
Hi @ecoruh, I think there is already PR open to fix this issue: https://github.com/SC5/serverless-mocha-plugin/pull/12.

**Comment by ecoruh** [comment]
Ah ok thanks.

**Comment by AlexMcConnell** [comment]
Similar error, but it looks like the reasons for mine are different, since the fix didn't work and I don't have the weird character replacement.

`Unhandled rejection Error: Cannot find module 'dynamodb-doc'`

**Comment by mpuittinen** [comment]
Thanks for the feedback, that has now been fixed, I'm about to release a new package version once I have all of the PRs merged.
