### ISSUE TITLE
Tests in a directory other than 'test'

### ISSUE THREAD

**Issue by johnsgp** [SC5/serverless-mocha-plugin#15]
How can I run tests that are not in the 'test' directory, either in a different hierarchy or a subdirectory of test?  Using serverless-mocha-plugin 0.5.6 with serverless 0.5.5, I tried

`sls function mocha-run path/to/tests`

but that gave

`Unhandled rejection Error: Cannot find module '...\test\path\to\tests.js'`

In other words, it always starts with 'test'.  I then tried putting path/to/tests below test, and referred to the test file name (mytest.js) like this:

`sls function mocha-run path/to/tests/mytest`

then got

```
...\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'toObjectPopulated' of undefined
  at ...\node_modules\serverless-mocha-plugin\index.js:206:54
```

**Comment by mpuittinen** [comment]
You should give the function name as a parameter to mocha-run, not the path to the test file. The mocha-run is provided as a convenience method to enable running the mocha tests created by function mocha-create. In case of more specific needs, I'd recommend using mocha directly, i.e. 

mocha path/to/tests
