### ISSUE TITLE
Tests fail if lambda connecting to private resource

### ISSUE THREAD

**Issue by scotty-p** [SC5/serverless-mocha-plugin#20]
Mocha tests use lambda-wrapper to run functions offline and test the output. If the lambda function needs to connect to a private resource, like an RDS database, the function times out and the test fails. Can the deployed lambda function be invoked instead of running locally?

**Comment by mpuittinen** [comment]
We could add capability into lambda wrapper to connect to a deployed Lambda function and run tests using that.

**Comment by mpuittinen** [comment]
Implemented capability to run the deployed function to lambda-wrapper + added the syntax required to run live lambdas to the test template. Published as package version 0.5.10

@scotty-p Can you check whether this enables you to run your tests against the deployed lambdas?

**Comment by scotty-p** [comment]
I can confirm this works! I had to raise the timeout of the tests from 2 seconds to 5 seconds.

Created a pull request to fix the way the test template creates the lambda function name.
