### ISSUE TITLE
Force user to set a stage name?

### ISSUE THREAD

**Issue by rafaljanicki** [SC5/serverless-mocha-plugin#21]
Hey,

I wonder if fetching all stages in case no is provided is safe. E.g. I have an environment set with 3 stages - dev, test & production. And I keep database credentials for each as my tests are executing IT tests as well. If I forgot to provide a stage name, there is a chance that my production database would be purged and filled with test data.

What do you think about forcing user to provide a stage name? Or at least do it in a serverless way and ask a user for the stage.

I can do a PR, but would like to discuss that before

**Comment by mpuittinen** [comment]
Hi! Please go ahead with the PR. Although sls function run, deploy does not require the user to give a stage, let’s do that with mocha-run just to be safe.
Basically, 
- if -s is provided, use that stage for tests in mocha-run
- if not, ask for the stage the “serverless” way

-Mikael

**Comment by mpuittinen** [comment]
Included in latest package version
