### ISSUE TITLE
Use templates when generating a test file

### ISSUE THREAD

**Issue by rafaljanicki** [SC5/serverless-mocha-plugin#24]
Hello,

I was thinking about introducing a simple template engine to handle generation of test files as those vary between projects and as sls-mocha-plugin already creates test files, why won't make it more powerful?

The behaviour would be quite simple - if file xxx.yyy exists, use it, otherwise use a predefined template.

For the engine I was thinking about something simple like EJS or doT.js. I haven't tried them yet, but it looks like they're old enough to be used.

What do you think?

**Comment by mpuittinen** [comment]
That’s a good idea, please go ahead. I was initially considering to create templates internally within the plugin, but ended up embedding the template to index.js for the sake of simplicity. Project level templates would provide optimal flexibility.

**Comment by mpuittinen** [comment]
@rafaljanicki I've merged your PR and published version 0.5.12 of the package. Please verify and close the issue in case the merge is OK.

**Comment by rafaljanicki** [comment]
Looks good, thanks
