### ISSUE TITLE
Conflicting with the core `sls invoke` command (v1)

### ISSUE THREAD

**Issue by rowanu** [SC5/serverless-mocha-plugin#28]
Once I've added this plugin to my Serverless (v1) project, I can't invoke my function via the usual "serverless invoke -f hello" command. I get this debug output:

```bash
$ serverless invoke -f hello

  Type Error ---------------------------------------------

     Cannot read property 'forEach' of undefined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'forEach' of undefined
    at PluginManager.getEvents (/Users/rowan/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/PluginManager.js:216:39)
    at PluginManager.run (/Users/rowan/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/classes/PluginManager.js:77:25)
    at Serverless.run (/Users/rowan/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/Serverless.js:77:33)
    at /Users/rowan/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/bin/serverless:18:50
```

Looking closer, the `commandDetails` variable in `PluginManager.js` (line 216) at run time is:

```javascript
{ usage: 'Invoke mocha tests for service / function',
  commands:
   { test:
      { usage: 'Invoke test(s)',
        lifecycleEvents: [Object],
        options: [Object] } } }
```

I'm just getting started with Serverless, but it looks like it's not expecting this object to have so many levels (i.e. it's expecting the `lifecycleEvents` property to be at the top level of `commandDetails`).

Is this a configuration issue on my side? I'm adding this snippet at the **bottom** of my `serverless.yml` file to load the plugin:

```yaml
plugins:
  - serverless-mocha-plugin
```

If I don't load this plugin, the `invoke` command works as expected.

**Comment by oipat** [comment]
I think it's a serverless issue since serverless documentation gives me the understanding that this kind of command nesting is allowed. See: https://github.com/serverless/serverless/issues/1987

**Comment by rowanu** [comment]
Thanks for the response! I'm still getting a hang of the framework. I'll track it in the upstream ticket.
