### ISSUE TITLE
Feature request: way to pass CLI args through to mocha

### ISSUE THREAD

**Issue by cdmcmahon** [SC5/serverless-mocha-plugin#36]
Say for example I am running my tests with the following command:

```bash
sls invoke test -f <function_name>
```

But I would like to use [mocha's feature](http://mochajs.org/#usage) `-g <pattern>` flag to only run tests that match a certain pattern, it would be great if there were a way to pass that into my above command and have it passed on to mocha using `mocha.setup({ g: pattern })`. One complication is that mocha shares some arguments with the package. My suggestion would be to prepend any mocha args with `mocha-` such that my final command in this example would be:

```bash
sls invoke test -f <function_name> -mocha-g <pattern>
```

If this is already a feature somehow and I missed it looking over the code/doc apologies and any help pointing me in the right direction would be appreciated. Otherwise, I'd be happy to contribute to help get this feature developed if you would like and would appreciate any input.

Thanks!

**Comment by mpuittinen** [comment]
Good idea. Will definitely consider it for the next version. If you submit a PR for the change, that would help to get that incorporated faster.

**Comment by mpuittinen** [comment]
@cdmcmahon  Do you have other needs than the -g option (grep). It seems that the capabilities we can set when using Mocha programatically are limited (see options in https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically). We'd need to implement a defined set of variables to support, e.g. 
```
    sls invoke test --grep <pattern>
```

**Comment by mpuittinen** [comment]
@cdmcmahon Implemented --grep / -G. Will be included in plugin version. Please let us know if other options are needed.

**Comment by Leandros** [comment]
I'd like to have mocha's `--require` available.

**Comment by kevde** [comment]
is there also a way to include --opts. I was trying to create an mocha-init every time I create tests to preload my assertion tools like chai and prepare some data
