### ISSUE TITLE
example ?

### ISSUE THREAD

**Issue by walshe** [SC5/serverless-mocha-plugin#40]
anyone got an example serverless project that uses this plugin, cannot get it to run

have added this to package.json

"scripts": {
	"test": "SLS_DEBUG=true serverless --stage dev invoke test"
  }

and when i run npm test I get this:

  **Serverless Error ---------------------------------------
 
     Trying to populate non string value into a string for
     variable ${opt:stage}. Please make sure the value of
     the property is a string.
 
  Stack Trace ---**

heres my serverless.yml

service: email-integration

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  apiKeys:
      - ${opt:stage}-${self:service}-api-key
  runtime: nodejs4.3

# you can overwrite defaults here
  stage: ${opt:stage}  # Set the default stage used. Default is dev
  region: eu-west-1     # Overwrite the default region used. Default is us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "arn:aws:sqs:*:*:${opt:stage}-emailtaskqueue"    #allow access to queue
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource: "*"    #allow to invoke other lambdas

  environment:
    ACCOUNT_ID : xxxxxx #813371197456  #644843699445
    STAGE : ${opt:stage}
    REGION : ${self:provider.region}
    SERVICE : ${self:service}

# you can add packaging information here
package:
  include:
#    - emailRequestListener/handler.js
#    - include-me-dir/**
  exclude:
    - emailRequestListener/test/**
#    - exclude-me-dir/**

functions:

  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  emailRequestListener:  #api gateway listening for incoming sendEmail requests
    handler: emailRequestListener/handler.emailRequestListener
    events:
      - http:
          path: sendEmail
          method: post
          private: false

  emailTaskConsumer:    #scheduled lambda that reads messages periodically from SQS queue and delegates to workers
    handler: emailTaskConsumer/handler.emailTaskConsumer
    timeout: 200         #200 seconds max
    events:
      - schedule: rate(1 minute)

  emailWorker:  #worker lambda to call email service provider
    handler: emailWorker/handler.emailWorker

plugins:
    - serverless-mocha-plugin

# you can add CloudFormation resource templates here
resources:
  Resources:

    EmailTaskDeadLetterQueue:   #email task dead letter queue
      Type: 'AWS::SQS::Queue'
      Properties:
        MessageRetentionPeriod: 1209600
        QueueName: ${opt:stage}-emailtaskdeadletterqueue

    EmailTaskQueue:  #email task queue
      Type: 'AWS::SQS::Queue'
      Properties:
        MessageRetentionPeriod: 1209600
        QueueName: ${opt:stage}-emailtaskqueue
        VisibilityTimeout : 30
        #RedrivePolicy:
        #    deadLetterTargetArn: arn:aws:sqs:${self:provider.environment.REGION}:${self:provider.environment.ACCOUNT_ID}:${opt:stage}-emailtaskdeadletterqueue
        #    maxReceiveCount: 3

`

**Comment by laardee** [comment]
@walshe hi, this plugin is included e.g. in  https://github.com/SC5/sc5-serverless-boilerplate

**Comment by laardee** [comment]
Oh, you added some code, could you wrap that with triple backticks, so it would be easier to read?

**Comment by laardee** [comment]
@walshe I got it reproduced. I'll try to figure out what is causing this issue ASAP. Thanks for reporting.
