### ISSUE TITLE
Run all tests in test folder

### ISSUE THREAD

**Issue by leeeomaaax** [SC5/serverless-mocha-plugin#47]
Today the plugin only run tests with matching function names. Would be great if the plugin ran all tests inside test folder on "sls invoke test". 

I've tried running tests directly with mocha but then I need to export environment variables that were on serverless.yml.

**Comment by laardee** [comment]
@leeeomaaax there could be a flag, like `--all` or `--include-all`. I have to think about that.

**Comment by leeeomaaax** [comment]
Ok @laardee , thanks! I'll also give it a look when I have a chance!

**Comment by mpuittinen** [comment]
@leeeomaaax @laardee Implemented without the --all flag in module version 1.5.0, i.e. in case other tests have been defined, those are also run.
