### ISSUE TITLE
Bit of guidance

### ISSUE THREAD

**Issue by scotty-p** [SC5/serverless-mocha-plugin#48]
G'day, 

I'm getting started with TDD and want to test outputs from specific methods/functions within a Lambda function. Some of these functions live in separate files in a lib folder. Is this possible? How would I go about this? 

Cheers

**Comment by laardee** [comment]
@scotty-p sorry about late reply 😞. For now, you need to use `mocha` to test other than handler functions. There is a related [issue](https://github.com/SC5/serverless-mocha-plugin/issues/47), so I'll close this one.
