### ISSUE TITLE
Command "invoke test" not found, Run "serverless help" for a list of all available commands.

### ISSUE THREAD

**Issue by railto** [SC5/serverless-mocha-plugin#49]
Just added this to an existing project that I'm trying to bring under test but anytime I run the commands provided in the readme it gives me a similar error to the one in the title.  Anyone had issues running this on a newer version of serverless?

Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.10.0
     Serverless Version: 1.14.0

**Comment by railto** [comment]
Never mind, turns out I had missed a step.

**Comment by fhackenb** [comment]
The problem is solved by adding:

`
plugins:
  - serverless-mocha-plugin
`
