### ISSUE TITLE
What else does this plugin do?

### ISSUE THREAD

**Issue by leeeomaaax** [SC5/serverless-mocha-plugin#50]
This is a questions and maybe a documentation update request.

From docs we have:
> This plugins does the following:
> 
> It provides commands to create and run tests manually
> It provides a command to create a function, which automatically also creates a test

Seems that the plugin also loads environment variables from serverless.yml. If it was only for the aliases commands mentioned I would be using plain mocha instead. So I was wondering, are there any other differences between running the tests with plain mocha and running it with `sls invoke test`?

**Comment by mpuittinen** [comment]
@leeomaax For now sls invoke test sets the env variables and then runs the tests. This may extend in the future (e.g. building the package and running tests on the actual code to be deployed). I clarified the docs to include the info. Thanks for the feedback.
