### ISSUE TITLE
Referenced variables in serverless.yml not expanded during invoke test

### ISSUE THREAD

**Issue by kaiyyyy** [SC5/serverless-mocha-plugin#53]
Hello, 

I am quite confused to this as I am still very new to serverless and TDD for serverless, however, in my serverless.yml, I have declared
```
provider:
  name: aws
  region: 'ap-northeast-1' 
```
where under the same provider, I have also written
```
environment:
    region: ${opt:region,self:provider.region}
```

However, over in my nodejs function, when I retrieve the variable via process.env.region to use in the AWS SDK, instead of 'ap-northeast-1' , I got ${opt:region,self:provider.region}. 

I also got the error when I following error when I try to use the RDS API
> err#  {"message":"Inaccessible host: `rds.'. This service may not be available in the `${opt:region,self:provider.region}' region.

May I know if this is supposed to happen? I know that the variable references are correctly declared as it works perfectly fine when deployed..

**Comment by mpuittinen** [comment]
Hi!

Tried this on my env (node 6, OS X) from the sc5-serveless-boilerplate (module version 1.3.5) and get consistently the right env out when running ‘sls invoke test’.
Can you provide step by step instructions how to reproduce the issue?

Cheers,

Mikael

**Comment by kaiyyyy** [comment]
Hello! Thank you for the response. This was what I did.

1. install serverless
2. use serverless to create a service
3. inside the service, I installed serverless-mocha-plugin locally
4. This is what I have inside the serverless.yml

```
> service: errorProducer
> 
> custom:
>     region : ${opt:region,self:provider.region}
>     
> plugins:
>   - serverless-mocha-plugin
> 
> provider:
>   name: aws
>   runtime: nodejs6.10
>   stage: dev #stage 
>   memorySize: 128 
>   region: 'ap-northeast-1' 
>   timeout: 10
>   
>   environment:
>     region: ${opt:region,self:provider.region}
>     
> functions:
>   hello:
>     handler: handler.hello
```

5. I used the default handler function and this was what I did inside the handler
```
'use strict';

var region = process.env.region;

module.exports.hello = (event, context, callback) => {

    console.log(region);
    callback(null, region);

};
```

6. I created the test using sls create test --function 
7. I changed nothing in the test and ran the test and this was the output

>   hello
> ${opt:region,self:provider.region}
>     √ implement tests here
> 
> 
>   1 passing (10ms)

My OS is Windows Server 2016. I appreciate the help you are giving me in this!

**Comment by mpuittinen** [comment]
Hi!

Thanks for the info. How did you run the test? Need to check if this is something Windows-related (different logic for env vars?)

Cheers,

Mikael

**Comment by kaiyyyy** [comment]
Hello!

Thanks for the reply.

I ran the test by running .\node_modules\.bin\serverless invoke test 

Thanks for looking into this!

**Comment by laardee** [comment]
@kaiyyyy thanks for reporting and especially the `Edit: Edit: I have tried reversing the version of "serverless" (not the mocha plugin) to ver 1.8.0 (was using 1.14.0 )and it works fine` part is useful. @mpuittinen I think the issue is related to this https://github.com/SC5/serverless-jest-plugin/pull/5. This https://github.com/SC5/serverless-mocha-plugin/blob/master/index.js#L139 part might be the issue here also. Now that I think, the backward compatibility of the jest plugin broke with my last PR. ..

**Comment by mpuittinen** [comment]
@kaiyyyy @laardee I've added tests for the env vars into the module tests and they are currently passing with both 1.14 and 1.15. Still need to investigate. 
@kaiyyy can you try the following in your env:
 1. clone the git project
 2. npm install
 3. npm run test

**Comment by laardee** [comment]
@mpuittinen integration tests use serverless 1.7.0 defined in the package.json (Travis don't have serverless installed by default 😁). If you change that and install dependencies again, I'm pretty sure that tests will fail.

**Comment by laardee** [comment]
I added another test that will fail if env vars are not correct (didn't change the sls version in the package.json yet). We need to figure out how to handle backward compatibility though...

**Comment by kaiyyyy** [comment]
Apologies for the late reply as I am only able to access the development environment during weekdays.

I have done the 3 steps and I have the following (i believe you are interested in this part? the whole thing is long)

>     √ tests setEnv with testFunction1 (env vars)
>     √ tests setEnv with testFunction1
>     √ tests setEnv with testFunction2
>

**Comment by kaiyyyy** [comment]
@laardee @mpuittinen @martinheidegger 

Hello!

I have just tested the latest updated version after the merge and now it works perfectly with serverless 1.16.1!

Thanks a lot for the help! I will close this issue later this day
