### ISSUE TITLE
sls invoke test error

### ISSUE THREAD

**Issue by chacaldev** [SC5/serverless-mocha-plugin#55]
When I run the command `sls invoke test` I receive the following error:

```
Type Error ---------------------------------------------
 
     vars.populateService(...).then is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: vars.populateService(...).then is not a function
    at serverless.service.load.then (/...omitted.../node_modules/serverless-mocha-plugin/index.js:147:12)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.12.1
```

I found a change in the same line of index.js file, referenced in the commit [70c1ee761b6c751be6a70969466a48ceae09fb9d](https://github.com/SC5/serverless-mocha-plugin/commit/70c1ee761b6c751be6a70969466a48ceae09fb9d), that generated the version 1.3.6.

I try the version 1.3.5 and have no errors.

**Comment by mpuittinen** [comment]
@chacaldev Is it possible for you to try a newer serverless version? Does that solve the issue?

**Comment by chacaldev** [comment]
I installed the newer version (1.16.1) and everything works fine! It solved the issue.

Thanks @mpuittinen.
