### ISSUE TITLE
Cannot run serverless-webpack before tests

### ISSUE THREAD

**Issue by lpgeiger** [SC5/serverless-mocha-plugin#57]
cross posted here: https://github.com/elastic-coders/serverless-webpack/issues/143

Seems like the test runner is not loading other plugins before running the tests. There is a suggestion at the discussion linked above. 
@laardee  any thoughts on this?

## Description
I'm trying to ensure that webpack runs before the testing plugin.

It appears tests are running the uncompiled code (not using webpack), and also using the node version. This means I'm not catching all the syntax errors lambda runtime does not support.

## Reproduction
It's a bit tricky to reproduce this error, since you'd have to compare the jest test run results to that of a deployed function. 
You can break the webpack integration by breaking the config file : 
```
module.exports = {
  entry: null,
...
````
The test runner will not catch this error, which implies that webpack is not running before the tests.
The only way to catch this is by running `serverless webpack serve`

## Additional Data

package.json
```
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-polyfill": "6.13.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-0": "^6.5.0",
    "serverless-jest-plugin": "^0.1.5",
    "serverless-webpack": "^1.0.0-rc.3",
    "webpack": "^1.13.1"
```
serverles.yml
```
plugins:
  - serverless-jest-plugin
  - serverless-webpack
```

**Comment by mpuittinen** [comment]
@laardee should we run the "package" method prior to invoking the tests? This may require some tweaking since the test scripts expect to find the source files in a specific path.
We could also add a check (warning) that verifies whether the node runtime defined for the service matches the current runtime.

**Comment by mpuittinen** [comment]
@lpgeiger @laardee Implemented a NodeJS runtime version check (warns if mismatch). Will be included in the next package version. Currently only warns about the mismatch.

**Comment by lpgeiger** [comment]
@mpuittinen Thanks that's actually really helpful for a newbie. About the first comment, I think it's important to use the serverless plugin tool chain. This may mean having a serverless method of invoking tests. What I mean is the default way of running tests by invoking `>jest` , will alway be out-of-band and not interact with the other serverless plugins.

**Comment by mpuittinen** [comment]
@lpgeiger This is fairly close, in 1.4, I already changed so that the tests are run from process.env.SERVERLESS_TEST_ROOT instead of the relative path ../ 
In my dev env (with a bit of tweaking), I'm able to do the following:
- sls package -p testPackage
- pushd testPackage; unzip service.zip; popd
- sls invoke test -r testPackage (a new option in the works)
which runs the tests on the files (webpack'ed) produced by sls package. Need to do some cleaning up before making that available. Optimally, I'd like to have e.g. an option nozip to sls package, which would just create the artifacts into the package directory (and remove the need for the separate unzip phase)

**Comment by lpgeiger** [comment]
@mpuittinen That's great. Looking forward. Let me know how I can test to give feedback.

**Comment by mpuittinen** [comment]
@lpgeiger the code is now in git, you can test it by installing the module from git instead of the npm repo and then trying e.g.
> sls package -p testBuild
> pushd testBuild
> unzip [yourServiceName].zip
> popd
> sls invoke test --root testBuild/
> rm -rf testBuild

**Comment by laardee** [comment]
@mpuittinen that's a good approach and seems to work like intended.

I don't think the packaging should be executed before tests under the hood by default -> when a test fails the error information will be quite hard to read, line numbers differ from source code etc. With this approach, you know that you will be running the tests against packaged code, not the source.

About the test template, should this be somehow implemented into mocha plugin

```javascript
if (process.env.SERVERLESS_MOCHA_PLUGIN_LIVE) {
  const mod = mochaPlugin.initLiveModule('hello');
  wrapped = lambdaWrapper.wrap(mod);
} else {
  const mod = require(process.env.SERVERLESS_TEST_ROOT + '/hello/index.js');
  wrapped = lambdaWrapper.wrap(mod, {
    handler: 'handler',
  });
}
```
When I tested this in an old project, the mocha plugins print out that I'm running the tests against code under 'testBuild/', but my old tests use the old wrapping style and it runs the code as before, from source.

The mocha plugin already has the lambda wrapper, so it could be something like 
```javascript
const wrapped = mochaPlugin.wrap('hello', '/hello/index.js');
```
or
```javascript
const wrapped = mochaPlugin.wrap({ functionName: 'hello', functionPath: '/hello/index.js' });
```
and the mochaPlugin.wrap would contain the logic that returns either live function or function from source/package directory. Something like this:
```javascript
const wrap = (functionName, functionPath) => {
  let mod;
  let options = {};
  if (process.env.SERVERLESS_MOCHA_PLUGIN_LIVE) {
    mod = mochaPlugin.initLiveModule(functionName);
  } else {
    mod = require(`${process.env.SERVERLESS_TEST_ROOT}${functionPath}`);
    options = { handler: 'handler' };
  }
  return lambdaWrapper.wrap(mod, options);
}
```

**Comment by mpuittinen** [comment]
--root option included in package version 1.4.1

**Comment by lpgeiger** [comment]
@mpuittinen Looks good will be trying shortly!

**Comment by mpuittinen** [comment]
@laardee implemented much of the code currently on the test template in mochaPlugin.getWrapper() (simplified the test files quite a bit and ensure that we have more control over the logic within the plugin)

**Comment by nenti** [comment]
Is this also going to be fixed for serverless-jest-plugin?
