### ISSUE TITLE
Command does not exit after running tests

### ISSUE THREAD

**Issue by vspedr** [SC5/serverless-mocha-plugin#60]
After following instructions, I wrote a couple of tests, and after I run them with
`SLS_DEBUG=* sls invoke test --stage ci -f githubNotify --compilers js:babel-register`
the tests pass, but the process will not exit (I need to Ctrl+C to force it).

Tests are as follows:
```
describe('githubNotify', () => {
  it('should return a HTTP 200 response', async () => {
    const result = await wrapped.run(payload);
    expect(result).to.have.property('statusCode', 200);
  });

  it('should throw error if payload is invalid', () => {
    expect(wrapped.run).to.throw();
  });
});
```
Other than that and commenting out the `before()` function, I did not modify the template.
I verified that my function returns as expected in both cases, and even if I run each test separately, both get stuck after passing.

Is there anything I'm missing?

**Comment by lukejagodzinski** [comment]
@vspedr I have the same problem. Did you manage to solve it?

**Comment by mpuittinen** [comment]
@vspedr @lukejagodzinski Try changing from arrow function to "traditional", i.e.
  it('should throw error if payload is invalid', function (done) {
    expect(wrapped.run).to.throw();
    done();
  });
I've had similar issues in some cases (not being able to pinpoint the exact circumstances) and considering to fallback to traditional for the default test template. (see issue #58 )

**Comment by lukejagodzinski** [comment]
@mpuittinen changing arrow functions to anonymous functions does not change anything. The problem we're facing is related with async/await. You can't use `done()` in the async function.

**Comment by ehthind** [comment]
@mpuittinen Any update on how to proceed with this issue ? 
It would be advantageous if we were able to pass the `--exit` flag though serverless-mocha-plugin to mocha so it exits as it used to in Mocha V3.

**Comment by KariHe** [comment]
#91
