### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cdelgadob** [SC5/serverless-mocha-plugin#62]
Is there a place where I can find examples?

I have the local dynamodb plugin configured and running, is it possible to start it via sls invoke test?

Thanks

**Comment by mpuittinen** [comment]
@cdelgadob I've added the possibility to run scripts before and after tests in v 1.7.0. The documentation includes examples how to start and stop serverless offline

**Comment by cdelgadob** [comment]
Perfect, I'll give it a try.

Thanks!

**Comment by cdelgadob** [comment]
Closing this one as it works as expected and the examples are perfect.
