### ISSUE TITLE
Environment check required

### ISSUE THREAD

**Issue by antsy** [SC5/serverless-mocha-plugin#63]
https://github.com/SC5/serverless-mocha-plugin/blob/1d521eb5c2549580840e54a20250678c16809df6/index.js#L243

This doesn't work with Windows filesystem.

**Comment by mpuittinen** [comment]
@antsy Fixed to use path.isAbsolute and path.join to ensure cross-platform compability

**Comment by mpuittinen** [comment]
Fixed in v 1.6.1
