### ISSUE TITLE
How to get stage from test code?

### ISSUE THREAD

**Issue by carlosjac** [SC5/serverless-mocha-plugin#68]
Hi

I have different sets of test data for each stage.
Is there any way to get the stage from test code?

Thanks!

**Comment by carlosjac** [comment]
Hi,

Maybe this change in utils.js do the trick

function setEnv(serverless, funcName) {

  const testOptions = serverless.processedInput.options || {};
  const serviceVars = serverless.service.provider.environment || {};
  let functionVars = {};
  if (funcName && serverless.service.functions[funcName]) {
    functionVars = serverless.service.functions[funcName].environment || {};
  }
  return Object.assign(
    process.env,
    serviceVars,
    functionVars,
    testOptions
  );
}

**Comment by mpuittinen** [comment]
One alternative way is to publish the stage as an envrironment variable is serverless.yml:
 
environment:
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}

That would also be deployed with the function, which may be useful in e.g. determining resource names (e.g. dynamotable-prod / dynamotable-dev) within the code.

-Mikael

**Comment by carlosjac** [comment]
Great solution.
Thanks!
