### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by Enase** [SC5/serverless-mocha-plugin#74]
Does someone has an experience of how to get a code coverage using this plugin?
Would be great to see any ideas or examples if any..

**Comment by gcphost** [comment]
You can use https://istanbul.js.org/ 

```json
  "scripts": {
     ...
    "test-local": "export SERVERLESS_TEST_ROOT=`pwd` ; ./node_modules/nyc/bin/nyc.js mocha --exit",
  },
```
