### ISSUE TITLE
Support for New NodeJS 4.3.2 Lambda API

### ISSUE THREAD

**Issue by joshwils82** [SC5/serverless-mocha-plugin#9]
I am having issues running tests using the new Lambda API.  The error I see is

TypeError: cb is not a function

It appears this may be due to using an older version of lambda-wrapper.

I am doing something wrong or does lambda-wrapper version need to updated?

**Comment by calam1** [comment]
You are correct about the lambda-wrapper version.  I just cloned https://github.com/SC5/lambda-wrapper, and the latest version is 0.0.6 - Just link it to this plugin, etc and you should get past that error.

**Comment by joshwils82** [comment]
Ok, but shouldn't this be updated in the package.json of the plugin?  How
would I go about linking to a different version?

**Comment by calam1** [comment]
To link do the following:

- Clone the lambda-wrapper repo, it will have the latest changes.  cd into that directory run "npm link"
- Clone the serverless-mocha-plugin. cd into that directory and run "npm link lambda-wrapper" then run "npm link" in the same directory.
- Go to your "serverless" project, the one you are deploying, not the framework.  Double check your package.json to see if the mocha-plugin is in your deps, not necessary, but more of a sanity check you are in the right directory/project.  run "npm link serverless-mocha-plugin"

Hope I put the correct info down in the above steps, as you can see there are a few of them.

**Comment by joshwils82** [comment]
Ok, thanks for the information.  Hopefully, we can also get the version
updated so we don't require the extra steps.

**Comment by mpuittinen** [comment]
The dependencies have now been fixed to point to newer lambda-wrapper versions and a new package (0.5.3) has beem published.
